name: Generate asdocs

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Apache Flex SDK
        uses: joshtynjala/setup-apache-flex-action@v2
        with:
          flex-version: "4.16.1"
          air-version: "50.0.1.1"
          accept-air-license: true

      - name: Generate docs
        run: asdoc -source-path ".\src\" -doc-classes basic_Main common_Main ControlsMain hud_Main menu3_Main -exclude-classes EvergreenVitalInfoIcons_view -library-path ".\lib\" -main-title "H3 Controls Documentation" -window-title "H3 Controls Documentation" -output ".\asdoc\"

      - name: Upload docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: .\asdoc

  deploy:
    needs: generate

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v2